<a href="https://colab.research.google.com/github/jubaljacob/Classification-Code-Templates/blob/main/Classification_Code_Templates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Common preparing tools

## Importing the libraries

In [74]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix


## Importing the dataset

In [75]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

## Feature Scaling

In [77]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Training the Logistic Regression model on the Training set

In [78]:
classifier_log_reg = LogisticRegression()
classifier_log_reg.fit(X_train, y_train)
y_pred = classifier_log_reg.predict(X_test)
acc_score_log_reg = accuracy_score(y_test, y_pred)
cm_log_reg = confusion_matrix(y_test, y_pred)
print(cm_log_reg)

[[103   4]
 [  5  59]]


# KNeighborsClassifier

In [79]:
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)
cm_knn = confusion_matrix(y_test, y_pred)
acc_score_knn = accuracy_score(y_test, y_pred)
print(cm_knn)

[[103   4]
 [  5  59]]


# SVM Linear

In [80]:
classifier_SVM_lin = SVC(kernel = 'linear')
classifier_SVM_lin.fit(X_train, y_train)
y_pred = classifier_SVM_lin.predict(X_test)
cm_SVM_lin = confusion_matrix(y_test, y_pred)
acc_score_SVM_lin = accuracy_score(y_test, y_pred)
print(cm_SVM_lin)

[[102   5]
 [  5  59]]


# SVM rbf

In [81]:
classifier_SVM_rbf = SVC(kernel = 'rbf')
classifier_SVM_rbf.fit(X_train, y_train)
y_pred = classifier_SVM_rbf.predict(X_test)
cm_SVM_rbf = confusion_matrix(y_test, y_pred)
acc_score_SVM_rbf = accuracy_score(y_test, y_pred)
print(cm_SVM_rbf)

[[102   5]
 [  3  61]]


# Naive Bayes

In [82]:
classifier_Bayes = GaussianNB()
classifier_Bayes.fit(X_train, y_train)
y_pred = classifier_Bayes.predict(X_test)
cm_Bayes = confusion_matrix(y_test, y_pred)
acc_score_bayes = accuracy_score(y_test, y_pred)
print(cm_Bayes)

[[99  8]
 [ 2 62]]


# Decison Tree

In [83]:
classifier_tree = DecisionTreeClassifier(criterion = 'entropy')
classifier_tree.fit(X_train, y_train)
y_pred = classifier_tree.predict(X_test)
cm_tree = confusion_matrix(y_test, y_pred)
acc_score_tree = accuracy_score(y_test, y_pred)
print(cm_tree)

[[103   4]
 [  4  60]]


# Random Forest

In [84]:
def best_est(n_estimators,X_train,X_test,y_train,y_test):
    classifier_rff = RandomForestClassifier(n_estimators= n_estimators, criterion='entropy', random_state=0)
    classifier_rff.fit(X_train,y_train)
    yy_pred_rf = classifier_rff.predict(X_test)
    return(accuracy_score(y_test, yy_pred_rf))
scores = {estimator: best_est(estimator, X_train, X_test, y_train, y_test) for estimator in range(1,100)}

best_tree_size = max(scores, key=scores.get)

print(best_tree_size)

45


In [85]:
classifier_forest = RandomForestClassifier(n_estimators = 45, criterion = 'entropy')
classifier_forest.fit(X_train, y_train)
y_pred = classifier_forest.predict(X_test)
cm_forest = confusion_matrix(y_test, y_pred)
acc_score_forest = accuracy_score(y_test, y_pred)
print(cm_forest)

[[103   4]
 [  4  60]]


In [86]:
print(f"score for Naive Bayes: {100*acc_score_bayes:.3f} % accuracy")
print(f"score for Decision Tree: {100*acc_score_tree:.3f} % accuracy")
print(f"score for Logistic Regression: {100*acc_score_log_reg:.3f} % accuracy")
print(f"score for K_NN: {100*acc_score_knn:.3f} % accuracy")
print(f"score for Forest: {100*acc_score_forest:.3f} % accuracy")
print(f"score for SVM linear: {100*acc_score_SVM_lin:.3f} % accuracy")
print(f"score for SVM kernel: {100*acc_score_SVM_rbf:.3f} % accuracy")

score for Naive Bayes: 94.152 % accuracy
score for Decision Tree: 95.322 % accuracy
score for Logistic Regression: 94.737 % accuracy
score for K_NN: 94.737 % accuracy
score for Forest: 95.322 % accuracy
score for SVM linear: 94.152 % accuracy
score for SVM kernel: 95.322 % accuracy
